http: add missing header bootlegged by boost < 1.72
httpserver.cpp:75:10: error: 'deque' in namespace 'std' does not name a template type
   75 |     std::deque<WorkItem*> queue;
      |          ^~~~~

(https://github.com/bitcoin/bitcoin/commit/a5929130223973636f3fd25fbfaf2953f2ec96a9)